version: "3.9"    
services:
  waltz:
    image: ghcr.io/finos/waltz:latest
    volumes:
      - ${PWD}/sealights:/mnt/sealights
    environment:
      - JAVA_OPTS=-javaagent:/mnt/sealights/sl-cd-agent.jar -Dsl.tokenFile=/mnt/sealights/sltoken.txt -Dsl.appName=TheWaltz -Dsl.branchName=master -Dsl.tags=script,container -Dsl.labId=integ_test_microservices -Dsl.includes="*org.finos.*"
    command: ["run"]
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:11
    #volume mount is needed to iniatlize database only
    #volumes:
    #  - ${PWD}/waltz-sample-data/database/pg/versions/postgres-dump-1.46.sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: waltz
      POSTGRES_DB: waltz
      POSTGRES_PASSWORD: waltz